- name: 1st play
  hosts: tower1.33b9.internal 
  tasks:
    - name: 1st task
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
    - name: 2nd task
      setup:
      register: result
    - name: 3rd Task
      debug:
        var: result
